export const dashboardData = {
  stats: {
    totalProjects: 12,
    documentsGenerated: 45,
    exportsThisMonth: 28,
    teamMembers: 5,
    storageUsed: 7.5,
    storageLimit: 20,
  },
  recentActivity: [
    {
      id: "1",
      type: "document_generated",
      project: "TaskFlow SaaS",
      item: "Product Requirements Doc",
      time: "2 hours ago",
    },
    {
      id: "2",
      type: "export_completed",
      project: "E-commerce Mobile App",
      item: "User Stories to Linear",
      time: "4 hours ago",
    },
    {
      id: "3",
      type: "source_added",
      project: "API Documentation",
      item: "GitHub Repository",
      time: "1 day ago",
    },
    {
      id: "4",
      type: "team_invite",
      project: "TaskFlow SaaS",
      item: "Mike joined the team",
      time: "2 days ago",
    },
    {
      id: "5",
      type: "project_created",
      project: "New Marketing Site",
      item: "Project Created",
      time: "3 days ago",
    },
  ],
  recentProjects: [
    {
      id: "1",
      name: "TaskFlow SaaS",
      description: "AI-powered project management platform for small dev teams",
      status: "active",
      lastUpdated: "2024-03-15T14:30:00Z",
      documentsCount: 8,
      collaborators: 3,
      progress: 65,
      type: "saas",
      starred: true,
      createdAt: "2024-01-20T09:00:00Z",
      owner: "Sarah Chen",
      tags: ["project management", "ai", "saas"],
      lastActivity: [],
    },
    {
      id: "2",
      name: "E-commerce Mobile App",
      description: "Mobile app for selling handmade crafts",
      status: "draft",
      lastUpdated: "2024-03-10T10:00:00Z",
      documentsCount: 3,
      collaborators: 2,
      progress: 20,
      type: "mobile",
      starred: false,
      createdAt: "2024-02-01T11:00:00Z",
      owner: "Mike Johnson",
      tags: ["mobile app", "ecommerce", "react native"],
      lastActivity: [],
    },
    {
      id: "3",
      name: "API Documentation",
      description: "Documentation for our public API",
      status: "complete",
      lastUpdated: "2024-03-01T16:00:00Z",
      documentsCount: 5,
      collaborators: 1,
      progress: 100,
      type: "api",
      starred: true,
      createdAt: "2024-02-15T14:00:00Z",
      owner: "Alex Garcia",
      tags: ["api", "documentation", "rest"],
      lastActivity: [],
    },
    {
      id: "4",
      name: "New Marketing Site",
      description: "Website redesign for lead generation",
      status: "active",
      lastUpdated: "2024-03-12T12:00:00Z",
      documentsCount: 2,
      collaborators: 4,
      progress: 40,
      type: "other",
      starred: false,
      createdAt: "2024-03-01T10:00:00Z",
      owner: "Emily White",
      tags: ["marketing", "website", "redesign"],
      lastActivity: [],
    },
  ],
}
